---
title: "Activity Analysis"
author: "Nikolas Bergum"
date: "5/8/2020"
output:
  pdf_document: default
---
 
```{r, include = FALSE}
library(readxl)
library(behavr)
library(ggetho)
library(dplyr)
library(zeitgebr)
library(tidyverse)
library(ggpubr)
library(car)
library(emmeans)
library(damr)
library(scopr)
library(sleepr)
library(testthat)
library(covr)
library(knitr)
library(ggthemes)
library(lme4)
library(lmerTest)
options(contrasts = c("contr.sum", "contr.poly"))
```

```{r message=FALSE}
circa <- read_excel( "../data/WT_McKO_activity.xlsx")
#str(circa)
#View(circa)
circa <- subset(circa, Cycle == "LD", select = c(id, t, Activity, Condition, Cycle))
#str(circa)
circa$Condition <- as.factor(circa$Condition)
circa$Cycle <- as.factor(circa$Cycle)
#str(circa)
circa$moving <- ifelse(circa$Activity > 0, "TRUE", "FALSE")
#mutate(circa, moving)
circa$moving <- as.logical(circa$moving)
circa$asleep <- ifelse(circa$Activity == 0, "TRUE", "FALSE")
#mutate(circa, asleep)
circa$moving <- as.logical(circa$moving)
circa$asleep <- as.logical(circa$asleep)
#str(circa)
circa <- as.data.table(circa)
setkey(circa, id)
metadata1 <- data.table(id = paste("Control LD", 1:9), Condition = c("WT"), Cycle = c("LD"))
metadata2 <- data.table(id = paste("KO LD", 1:7), Condition = c("McKO"), Cycle = c("LD"))
#metadata2
metadata12 <- merge(metadata1, metadata2, all = TRUE)
#metadata12
setkey(metadata12, id)
circadt <- behavr(circa, metadata12)
#str(circadt)
circadt <- circadt[, phase := ifelse(t %% hours(24) < hours(12), "D", "L")]
summary_circa <- 
  rejoin(circadt[,
           .(activity_all = mean(Activity),
             activity_light = mean(Activity[phase == "D"]),
             activity_dark = mean(Activity[phase == "L"])
             ),
           ,by=id])
summary_circa <- melt(summary_circa, measure.vars = patterns("activity_"),
                          variable.name = "phase", value.name = "activity")
```

### Activity/Inactivity 24-hour Graphs

```{r}
activity_plot <- ggetho(circadt, aes(x=t, y=Activity, colour=Condition), time_wrap = hours(24)) +
       stat_pop_etho() +
       stat_ld_annotations(height=1, alpha=0.1, outline = NA, x_limits=c(0,86400)) +
       scale_y_continuous(name = "Activity (a.u.)") +
       scale_color_hue(name = "Genotype") + 
       scale_fill_hue(name = "Genotype") +
       theme_bw()

activity_plot

#ggsave(filename="../figures/activity_plot.svg", plot=activity_plot, height=4, width=7)

inactivity_plot <- ggetho(circadt, aes(y=asleep, colour=Condition), time_wrap = hours(24)) +
      stat_pop_etho() +
      stat_ld_annotations(height=1, alpha=0.1, outline = NA, x_limits=c(0,86400)) +
      scale_y_continuous(name= "Fraction of time inactive",labels = scales::percent) +
      scale_color_hue(name = "Genotype") + 
      scale_fill_hue(name = "Genotype") +
      theme_bw()

inactivity_plot

#ggsave(filename="../figures/inactivity_plot.svg", plot=inactivity_plot, height=4, width=7)
```



```{r}
summary_brah <- 
  rejoin(circadt[,
           .(sleep_fraction = mean(asleep)),
           by=id])
#summary_brah
#ggplot(summary_brah, aes(x=Condition, y=sleep_fraction, fill= Condition)) + 
#  geom_boxplot(outlier.colour = NA) +
#  geom_jitter(alpha=.5) +
#  scale_y_continuous(name= "Fraction of time sleeping",labels = scales::percent)
circadt[, phase := ifelse(t %% hours(24) < hours(12), "L", "D")]
summary_guys <- 
  rejoin(circadt[,
           .(sleep_fraction_all = mean(asleep),
             sleep_fraction_light = mean(asleep[phase == "L"]),
             sleep_fraction_dark = mean(asleep[phase == "D"])
             ),
           ,by=id])
#ggplot(summary_guys, aes(x=Condition, y=sleep_fraction_dark, fill= Condition)) + #geom_boxplot(outlier.colour = NA) +geom_jitter(alpha=.5) +
#  scale_y_continuous(name= "Fraction of time sleeping",labels = scales::percent)
summary_melty <- melt(summary_guys, measure.vars = patterns("sleep_fraction_"),
                          variable.name = "phase", value.name = "sleep_fraction")
#ggplot(summary_melty, aes(x=phase, y=sleep_fraction, fill=Condition)) + 
#  geom_boxplot(outlier.colour = NA) +
#  geom_jitter(alpha=.5) +
#        facet_grid(Cycle ~ .) +
#  scale_y_continuous(name= "Fraction of time sleeping",labels = scales::percent)
#summary_melty
pairwise.wilcox.test(summary_melty[Condition=="WT", sleep_fraction_all], 
                     summary_melty[Condition=="KO", Condition])
model <- aov(sleep_fraction ~ Condition, summary_melty)
summary(model)
bout_circadt <- bout_analysis(asleep, circadt)
bout_circadt <- bout_circadt[asleep == TRUE, -"asleep"]
#ggetho(bout_circadt, aes(y=duration / 60, colour=Condition), time_wrap = hours(24)) + 
#      stat_pop_etho() + 
#      scale_y_continuous(name= "Bout length (min)")
bout_circadt[,
        .(n_bouts = .N,
          mean_bout_length = mean(duration)),
        by=id]
bout_circadt_second_day <- bout_circadt[t %between%  c(days(1), days(1) + hours(12))]
bout_circadt_second_day[, t:= t - days(1)]
bout_summaryy <- bout_circadt_second_day[,.(
                      latency = t[1], # the first bout is at t[1] 
                      first_bout_length = duration[1],
                      latency_to_longest_bout = t[which.max(duration)],
                      length_longest_bout = max(duration),
                      n_bouts = .N,
                      mean_bout_length = mean(duration)
                      ),
                      by=id]
bout_circadt_second_day[, t:= t - days(1)]
bout_summaryy <- bout_circadt_second_day[,.(
                      latency = t[1], # the first bout is at t[1] 
                      first_bout_length = duration[1],
                      latency_to_longest_bout = t[which.max(duration)],
                      length_longest_bout = max(duration),
                      n_bouts = .N,
                      mean_bout_length = mean(duration)
                      ),
                      by=id]
#ggplot(rejoin(bout_summaryy), aes(n_bouts, mean_bout_length, colour=Condition)) +
#    geom_point() +
#    facet_grid(Condition ~ .) + 
#    scale_x_continuous(name="Number of bouts") +
#    scale_y_continuous(name="Average bout duration (s)")
overall_summaryy <- summary_guys[bout_summaryy]
#ggplot(overall_summaryy, aes(latency / 60, sleep_fraction_light, colour=Condition)) +
#    geom_point() +
#    geom_smooth(method="lm", alpha=.1)+
#    facet_grid(Condition ~ .)
```


```{r fig.height=4, fig.width=4}
#str(circa)
#str(circadt) #metadata table
#ggetho(circadt, aes(x=t, z=Activity)) + stat_bar_tile_etho()
#ggetho(circadt, aes(y=asleep, colour=Condition), time_wrap = hours(24)) +
#      stat_pop_etho() +
#      stat_ld_annotations() +
#      facet_grid(Cycle ~ .) +
#      scale_y_continuous(name= "Fraction of time sleeping",labels = scales::percent)
summary_circa$Condition <- as.factor(summary_circa$Condition)
summary_circa$phase <- as.factor(summary_circa$phase)
summary_circaLD <- filter(summary_circa, phase != "activity_all")
summary_circaLD
SumStatcirca <- summarize(group_by(summary_circaLD, Condition, phase),
n = n(),
mean = mean(activity),
sd = sd(activity),
se = sd/sqrt(n))
SumStatcirca
#qplot(x = phase, y = mean, colour = Condition, group = Condition, data = SumStatcirca) + geom_line() + geom_errorbar(aes(ymin=mean-se, ymax=mean+se))+ scale_y_continuous(name= "Activity: x-y movement")

#ggplot(SumStatcirca, aes(phase, mean)) + 
#geom_bar(aes(fill = Condition), stat="identity", position=position_dodge(), width=.5) + #geom_errorbar(aes(ymin=mean-se, ymax=mean+se, fill = Condition), width=.2, position=position_dodge(0.47)) +
#geom_signif(y_position=c(0.08, 0.19), xmin=c(0.8, 1.8), xmax=c(1.2, 2.2),annotation=c("ns", "**"), tip_length=0) + scale_fill_manual(values = c("red", "blue")) 

#ggplot(SumStatcirca, aes(phase, mean)) + 
#geom_bar(aes(fill = Condition), stat="identity", position=position_dodge(), width=.5) + #geom_errorbar(aes(ymin=mean-se, ymax=mean+se, fill = Condition), width=.2, position=position_dodge(0.47)) +
#geom_signif(y_position=c(0.08, 0.19), xmin=c(0.8, 1.8), xmax=c(1.2, 2.2),annotation=c("ns", "**"), tip_length=0) + scale_fill_manual(values = c("red", "blue"))
```

### Activity Quantified Bar Plots

```{r}
SumStatcirca$phase <- recode_factor(SumStatcirca$phase, activity_light = "Light", activity_dark = "Dark")

#SumStatcirca

act_quant_plot <- ggplot(SumStatcirca, aes(phase, mean)) + 
  geom_bar(aes(fill = Condition), stat="identity", position=position_dodge(), width=.75) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se, fill = Condition), width=.2, position=position_dodge(0.75)) +
  #mcko vs wt within light condition
  #geom_signif(y_position=c(0.23, 0.135), xmin=c(1.85, 0.85), xmax=c(2.15, 1.15),annotation=c("**", "n.s."), tip_length=0.02) +
  #light vs dark within genotype
  #geom_signif(y_position=c(0.26, 0.29), xmin=c(0.85, 1.1), xmax=c(1.9, 2.15),annotation=c("****", "**"), tip_length=0.02) +
  theme_bw() + 
  labs(fill = "Genotype",
       x = "Phase",
       y = "Mean Activity (a.u.)") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.3)))


summary_circaLD <- summary_circaLD %>% 
  mutate(phase = recode_factor(phase, activity_light = "Light", activity_dark = "Dark"))

act_quant_plot <- act_quant_plot +
  geom_point(data=summary_circaLD, aes(x=phase, y=activity, fill=Condition), position = position_dodge(width = 0.75)) +
  theme_bw()

act_quant_plot

#ggsave(filename="../figures/activity_quantified_plot.svg", plot=act_quant_plot, height=4, width=5)
```



```{r echo=FALSE, fig.height=3, fig.width=6}
summary_melty$Condition <- as.factor(summary_melty$Condition)
summary_melty$phase <- as.factor(summary_melty$phase)
summary_meltyLD <- filter(summary_melty, phase != "sleep_fraction_all")
knitr::kable(summary_meltyLD)
SumStaty <- summarize(group_by(summary_meltyLD, Condition, phase),
n = n(),
mean = mean(sleep_fraction),
sd = sd(sleep_fraction),
se = sd/sqrt(n))
#qplot(x = phase, y = mean, colour = Condition, group = Condition, data = SumStaty) + geom_line() + #geom_errorbar(aes(ymin=mean-se, ymax=mean+se))+ scale_y_continuous(name= "Fraction of time sleeping",labels = scales::percent)
#SumStaty
```

### Inactivity Quantified Bar Plots

```{r}
SumStaty$phase <- recode_factor(SumStaty$phase, sleep_fraction_light = "Light", sleep_fraction_dark = "Dark")


inact_quant_plot <- ggplot(SumStaty, aes(phase, mean)) + 
  geom_bar(aes(fill = Condition), stat="identity", position=position_dodge(), width=.75) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se, fill = Condition), width=.2, position=position_dodge(0.75)) +
  #mcko vs wt within light condition
  #geom_signif(y_position=c(0.85,0.7), xmin=c(0.85, 1.85), xmax=c(1.15, 2.15),annotation=c("n.s.", "**"), tip_length=0.02) +
  #light vs dark within genotype
  #geom_signif(y_position=c(0.95, 1.05), xmin=c(0.85, 1.1), xmax=c(1.9, 2.15),annotation=c("****", "***"), tip_length=0.02) +
  scale_y_continuous(labels = scales::percent) +
  theme_bw() +
  labs(fill = "Genotype",
       x = "Phase",
       y = "Fraction of time inactive") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.3)), labels = scales::percent)

summary_melty <- summary_melty %>% filter(phase != "sleep_fraction_all") %>% 
  mutate(phase = recode_factor(phase, sleep_fraction_light = "Light", sleep_fraction_dark = "Dark"))

inact_quant_plot <- inact_quant_plot +
  geom_point(data=summary_melty, aes(x=phase, y=sleep_fraction, fill=Condition), position = position_dodge(width = 0.75))

inact_quant_plot

#ggsave(filename="../figures/inactivity_quantified_plot.svg", plot=inact_quant_plot, height=4, width=5)
```

```{r}
summary_melty$Condition <- as.factor(summary_melty$Condition)
summary_melty$phase <- as.factor(summary_melty$phase)
summary_melty$id <- as.factor(summary_melty$id)

summary_circaLD$id <- as.factor(summary_circaLD$id)
summary_meltyLD$id <- as.factor(summary_meltyLD$id)

act_lmer <- lmer(activity ~ Condition*phase + (1|id), data = summary_circaLD)
car::Anova(act_lmer, type = 3)
emmeans(act_lmer, pairwise ~ phase|Condition)$contrasts
emmeans(act_lmer, pairwise ~ Condition|phase)$contrasts

inact_lmer <- lmer(sleep_fraction ~ Condition*phase + (1|id), data = summary_meltyLD)
car::Anova(inact_lmer, type="3")
emmeans(inact_lmer, pairwise ~ phase|Condition)$contrasts
emmeans(inact_lmer, pairwise ~ Condition|phase)$contrasts
```

