---
title: "RNAscope-McKO-old-probe"
author: "CT Berezin"
date: "11/23/2021"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r}
library(tidyverse)
library(MESS)
library(ggpubr)
library(ggthemes)
```

```{r}
#creating the dataframe
genotype <- c("WT", "WT", "WT", "WT", "WT",
              "McKO", "McKO", "McKO", "McKO", "McKO", "McKO")
mouse <- c("17", "pup1-1", "pup1-2", "31", "90",
           "98", "pup1", "pup2", "pup4", "pup3", "pup2-2")
positive <- c(16, 42, 63, 3, 58,
              9, 46, 6, 19, 17, 19)
total <- c(17, 42, 68, 3, 67,
           15, 107, 7, 33, 21, 22)

data <- tibble(genotype, mouse, positive, total)

data <- mutate(data,
               percent = positive/total*100)
```

```{r}
#checking normality, variance, etc.
shapiro.test(data$percent)
morlm <- lm(percent ~ genotype, data)

resid <- rstandard(morlm)
yhat <- morlm$fitted.values
ggplot(data, aes(yhat, resid)) +
  geom_point()
car::leveneTest(percent ~ genotype, data)
#null hyp = variances are equal, fails
qqnorm(resid)
abline(0,1, lty=2)
```


```{r}
#Welch's t-test OK with non-homogenous variance
data %>% group_by(genotype) %>% summarise(sd=sd(percent))

t.test(percent ~ genotype, data)
power_t_test(n=5, delta=94.66637-68.93279,
             sd=5.63, ratio=1.2,
             sd.ratio=17.953801/5.631853,
             type="two.sample", alternative="one.sided")

stat.test <- compare_means(percent ~ genotype, data, method = "t.test")
```

```{r}
plot <- ggplot(data, aes(genotype, percent)) +
  geom_point(alpha=0.75) +
  stat_summary(fun = 'mean', geom="bar", aes(alpha=0.5)) +
  stat_summary(fun.data = mean_se, geom = "errorbar", width=.1, alpha=0.5) +
  theme_few() +
  theme(legend.position = "none") +
  labs(y="% ipRGCs with MOR mRNA",
       title = "RNAscope labeling of MOR mRNA") +
  geom_bracket(
    aes(xmin = "WT", xmax = "McKO", label = signif(p, 2)),
    data = stat.test, y.position = 110) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))
plot
ggsave("../figures/RNAscope_McKO_old_probe.png",
       plot=plot, height=3, width=3)
```