---
title: "RNAscope-McKO-new-probe"
author: "C-T Berezin"
date: "11/21/2021"
output:
  pdf_document: default
  html_document: default
---

```{r}
#analysis of MOR McKO validation using new RNAscope probe
library(tibble)
library(dplyr)
library(stringr)
library(ggplot2)
library(ggpubr)
library(ggthemes)
```

```{r}
#creating the data frame from values logged on google sheet
genotype <- c("WT", "WT", "WT", "WT", "McKO", "McKO", "McKO", "McKO")
sex <- c("F", "F", "M", "M", "F", "F", "M", "M")
number <- c(46, 47, 6, 77, 95, 98, 58, 92)
positive <- c(13, 17, 7, 13, 0, 1, 2, 4)
total <- c(16, 17, 7, 14, 1, 9, 6, 19)

data <- tibble(genotype, sex, number, positive, total)

data <- mutate(data,
                number = str_c(number),
                percent = positive/total*100)

sumstats <- data %>% group_by(genotype) %>%
         summarise(n = n(),
                   mean = mean(percent),
                   sd = sd(percent))
```

```{r}
#assessing normality
shapiro.test(data$percent)

#creating linear model and checking assumptions
morlm <- lm(percent ~ genotype, data)

resid <- rstandard(morlm)
yhat <- morlm$fitted.values
ggplot(data, aes(x=yhat, y=resid)) +
  geom_point()

qqnorm(resid)
abline(0, 1, lty = 2)

#t-test to assess whether genotype predicts percent of positive MOR+ ipRGCs
#it does - statistically significant decrease in McKO versus WT
t.test(percent ~ genotype, data)

#checking for a sex difference, there is none
t.test(percent ~ sex, data)


#checking the power
wts_only <- data %>% filter(genotype == "WT")
sd(wts_only$percent)
#sd is 8.85
mckos_only <- data %>% filter(genotype == "McKO")
#calculating delta (change in means between groups)
mean(wts_only$percent) - mean(mckos_only$percent)
#delta is 77.15
power.t.test(n=4, delta=77.15, sd=8.85, type = "one.sample", alternative="one.sided")
#power is 1

range(wts_only$percent)
range(mckos_only$percent)
```

```{r}
data <- data %>% 
  mutate(genotype = fct_relevel(genotype, c("WT", "McKO")))

mcko_plot <- ggplot() +
  stat_summary(data=data, aes(genotype, percent, fill=genotype), fun = 'mean', geom="bar") +
  geom_errorbar(data=sumstats, aes(genotype, ymin=mean-sd, ymax=mean+sd), width=0.2) +
  geom_point(data=data, aes(genotype, percent), size=2) +
  theme_bw() %+replace%
  theme(legend.position = "none") +
  labs(x="",
       y="% ipRGCs with MOR mRNA") +
  geom_signif(y_position=109, xmin=1, xmax=2, annotation="***", tip_length=0.02) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2)),
                     labels = function(x) paste0(x, "%"),
                     breaks = seq(0, 100, by = 25))

mcko_plot

ggsave(filename="../figures/RNAscope_McKO.png", plot=mcko_plot, height=4, width=3)
```