---
title: "Sleep Bout Analysis"
author: "CT Berezin"
date: "3/29/2022"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(lme4)
library(emmeans)
```

```{r}
bouts <- read.csv("../data/WT_McKO_combined_bouts.csv",
                      fileEncoding = 'UTF-8-BOM')
bouts <- bouts %>% mutate(Time = mdy_hms(Time),
                          Sleep.Stage = as.factor(Sleep.Stage),
                          Genotype = as.factor(Genotype),
                          Transmitter = as.factor(Transmitter))

bouts <- bouts %>% mutate(Hour = hour(Time))
bouts <- bouts %>% mutate(ZT = Time + hours(18))
bouts <- bouts %>% mutate(ZT = hour(ZT))

bouts <- bouts %>% dplyr::mutate(phase = as.factor(ifelse(ZT>11, "dark", "light")))

head(bouts)
```

```{r}
SumStats_daily <- bouts %>% group_by(Genotype, Transmitter, Sleep.Stage, Day) %>% 
  summarise(n_bouts = n(),
            total_duration = sum(Duration),
            min_bout_length = min(Duration),
            mean_bout_length = mean(Duration),
            max_bout_length = max(Duration),
            sd_bout_length = sd(Duration))
head(SumStats_daily)

SumStats_daily_n <- SumStats_daily %>% group_by(Genotype, Transmitter, Sleep.Stage) %>% 
  summarise(mean_n_bouts_day = mean(n_bouts))
head(SumStats_daily_n)

SumStats_avg <- bouts %>% group_by(Genotype, Transmitter, Sleep.Stage) %>% 
  summarise(min_bout_length = min(Duration),
            mean_bout_length = mean(Duration),
            max_bout_length = max(Duration),
            sd_bout_length = sd(Duration))
head(SumStats_avg)

SumStats_phase <- bouts %>% group_by(Genotype, Transmitter, Sleep.Stage, phase) %>% 
  summarise(n_bouts = n(),
            total_duration = sum(Duration),
            min_bout_length = min(Duration),
            mean_bout_length = mean(Duration),
            max_bout_length = max(Duration),
            sd_bout_length = sd(Duration))
head(SumStats_phase)

SumStats_phase_n <- SumStats_phase %>% group_by(Genotype, Transmitter, Sleep.Stage, phase) %>% 
  summarise(mean_n_bouts_day = mean(n_bouts))
head(SumStats_phase_n)
```

```{r}
SumStats_avg %>% group_by(Genotype, Sleep.Stage) %>% 
  summarise(n = n(),
            mean_bout_length = mean(mean_bout_length),
            min_bout_length = min(min_bout_length),
            max_bout_length = max(max_bout_length))

SumStats_phase_grps <- SumStats_phase %>% group_by(Genotype, Sleep.Stage, phase) %>% 
  summarise(n = n(),
            mean_bout_length = mean(mean_bout_length),
            min_bout_length = min(min_bout_length),
            max_bout_length = max(max_bout_length))
head(SumStats_phase_grps)

SumStats_phase_n_grps <- SumStats_phase_n %>% group_by(Genotype, Sleep.Stage, phase) %>% 
  summarise(n = n(),
            mean_n_bouts_day = mean(mean_n_bouts_day))
head(SumStats_phase_n_grps)
```

```{r}
lm_n_bouts <- lmer(mean_n_bouts_day ~ Sleep.Stage * phase * Genotype + (1 | Transmitter), data=SumStats_phase_n)
#plot(lm_n_bouts, type=c("p","smooth"), col.line=1)
#lattice::qqmath(lm_n_bouts)
anova(lm_n_bouts)
emmeans(lm_n_bouts, pairwise ~ Genotype | Sleep.Stage * phase)$contrasts

lm_mean_length <- lmer(mean_bout_length ~ Sleep.Stage * phase * Genotype + (1 | Transmitter), data=SumStats_phase)
plot(lm_mean_length, type=c("p","smooth"), col.line=1)
lattice::qqmath(lm_mean_length)
anova(lm_mean_length)
emmeans(lm_mean_length, pairwise ~ Genotype | Sleep.Stage * phase)$contrasts

lm_max_length <- lmer(max_bout_length ~ Sleep.Stage * phase * Genotype + (1 | Transmitter), data=SumStats_phase)
#plot(lm_max_length, type=c("p","smooth"), col.line=1)
#lattice::qqmath(lm_max_length)
anova(lm_max_length)
emmeans(lm_max_length, pairwise ~ Genotype | Sleep.Stage * phase)$contrasts
```

```{r}
SumStats_phase %>% filter(Sleep.Stage == "S" & phase == "light") %>% 
  ggplot(aes(x=Genotype, y=mean_bout_length)) +
  stat_summary(fun = 'mean', geom="bar") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width=.2) +
  geom_point()
```

