---
title: "Sleep Bout Analysis"
author: "CT Berezin"
date: "3/29/2022"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(lme4)
library(emmeans)
```

```{r}
bouts <- read.csv("../data/WT_McKO_combined_bouts.csv",
                      fileEncoding = 'UTF-8-BOM')
bouts <- bouts %>% mutate(Time = mdy_hms(Time),
                          Sleep.Stage = as.factor(Sleep.Stage),
                          Genotype = as.factor(Genotype),
                          Transmitter = as.factor(Transmitter))

bouts <- bouts %>% mutate(Hour = hour(Time))
bouts <- bouts %>% mutate(ZT = Time + hours(18))
bouts <- bouts %>% mutate(ZT = hour(ZT))

bouts <- bouts %>% dplyr::mutate(phase = as.factor(ifelse(ZT>11, "dark", "light")))

head(bouts)
```

```{r}
SumStats_daily <- bouts %>% group_by(Genotype, Transmitter, Sleep.Stage, Day, phase) %>% 
  summarise(n_bouts = n(),
            total_duration = sum(Duration),
            min_bout_length = min(Duration),
            mean_bout_length = mean(Duration),
            max_bout_length = max(Duration),
            sd_bout_length = sd(Duration))
head(SumStats_daily)

SumStats_phase <- SumStats_daily %>% group_by(Genotype, Transmitter, Sleep.Stage, phase) %>% 
  summarise(daily_bouts = mean(n_bouts),
            daily_duration = mean(total_duration),
            min_bout = min(min_bout_length),
            mean_bout = mean(mean_bout_length),
            max_bout = max(max_bout_length))
head(SumStats_phase)
```

```{r}
SumStats_phase_grps <- SumStats_phase %>% group_by(Genotype, Sleep.Stage, phase) %>% 
  summarise(n = n(),
            daily_bout_len = mean(daily_bouts),
            daily_dur = mean(daily_duration),
            avg_bout_length = mean(mean_bout),
            min_bout_length = min(min_bout),
            max_bout_length = max(max_bout))
SumStats_phase_grps
```

```{r}
head(SumStats_phase)


lm_n_bouts <- lmer(daily_bouts ~ Sleep.Stage * phase * Genotype + (1 | Transmitter), data=SumStats_phase)
plot(lm_n_bouts, type=c("p","smooth"), col.line=1)
lattice::qqmath(lm_n_bouts)
anova(lm_n_bouts)
emmeans(lm_n_bouts, pairwise ~ Genotype | Sleep.Stage * phase)$contrasts

lm_mean_length <- lmer(mean_bout ~ Sleep.Stage * phase * Genotype + (1 | Transmitter), data=SumStats_phase)
plot(lm_mean_length, type=c("p","smooth"), col.line=1)
lattice::qqmath(lm_mean_length)
anova(lm_mean_length)
emmeans(lm_mean_length, pairwise ~ Genotype | Sleep.Stage * phase)$contrasts


lm_max_length <- lmer(max_bout ~ Sleep.Stage * phase * Genotype + (1 | Transmitter), data=SumStats_phase)
#plot(lm_max_length, type=c("p","smooth"), col.line=1)
#lattice::qqmath(lm_max_length)
anova(lm_max_length)
emmeans(lm_max_length, pairwise ~ Genotype | Sleep.Stage * phase)$contrasts

lm_duration <- lmer(daily_duration ~ Sleep.Stage * phase * Genotype + (1 | Transmitter), data=SumStats_phase)
#plot(lm_duration, type=c("p","smooth"), col.line=1)
#lattice::qqmath(lm_duration)
anova(lm_duration)
emmeans(lm_duration, pairwise ~ Genotype | Sleep.Stage * phase)$contrasts
```

```{r}
SumStats_phase$Sleep.Stage <- recode_factor(SumStats_phase$Sleep.Stage, S = "SWS", P = "REM", X = "Artifact", W = "Wake")

daily_duration_plot <- SumStats_phase %>% filter(Sleep.Stage != "Artifact") %>% 
  ggplot(aes(x=phase, y=(daily_duration/3600))) +
  facet_wrap(~Sleep.Stage, scales="free_y") +
  geom_boxplot(aes(color=Genotype)) +
  ylab("Total daily duration (h)") +
  theme_bw()
  
daily_duration_plot
#ggsave(filename="../figures/daily_duration_plot.svg", plot=daily_duration_plot, height=4, width=7)

length_phase_plot <- SumStats_phase %>% filter(Sleep.Stage != "Artifact") %>% 
  ggplot(aes(x=phase, y=mean_bout)) +
  facet_wrap(~Sleep.Stage, scales="free_y") +
  geom_boxplot(aes(color=Genotype)) +
  ylab("Average bout length (s)") +
  theme_bw()

length_phase_plot
#ggsave(filename="../figures/length_phase_plot.svg", plot=length_phase_plot, height=4, width=7)
```

